name: Rainix CI
on: [push]

jobs:
  standard-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        task: [rainix-rs-test, rainix-rs-artifacts]
        include:
          # We don't need to do rust static analysis on multiple platforms
          - os: ubuntu-latest
            task: rainix-rs-static
      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      DEPLOYMENT_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PRIVATE_KEY || secrets.PRIVATE_KEY_DEV }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix develop --command rainix-rs-prelude
      - name: Run ${{ matrix.task }}
        env:
          ETH_RPC_URL: ${{ vars.CI_DEPLOY_SEPOLIA_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.EXPLORER_VERIFICATION_KEY }}
        run: nix develop --command ${{ matrix.task }}

      - name: Build for wasm target
        run: nix develop -c cargo build --target wasm32-unknown-unknown